---
- name: Install auditd
  apt:
    name: auditd
    state: present

- name: Install audispd-plugins
  apt:
    name: audispd-plugins
    state: present

- name: Enable auditd
  service:
    name: auditd
    state: started
    enabled: yes

- name: Add auditd to grub config
  replace:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX="((:?(?!{{ item.option }}={{ item.value }}).)*?)"$'
    replace: 'GRUB_CMDLINE_LINUX="\1 {{ item.option }}={{ item.value }}"'
    validate: /bin/sh %s
  loop:
    - option: audit
      value: 1
    - option: audit_backlog_limit
      value: 8192
  loop_control:
    label: "{{ item.option }}"
  notify:
    - update-grub

- name: Set auditd rules
  template:
    src: auditd_rules.j2
    dest: /etc/audit/rules.d/audit.rules
    owner: root
    group: root
    mode: '640'
  notify:
    - auditd-rules-reload