---
- name: Enable journald
  service:
    name: systemd-journald
    state: started
    enabled: yes

- name: Update journald config
  template:
    src: journald_conf.j2
    dest: /etc/systemd/journald.conf
    owner: root
    group: root
    mode: '644'
  notify:
    - journald-restart