---
- name: Install libpam-pwquality
  apt:
    name: libpam-pwquality
    state: present

- name: Set minimum password length
  lineinfile:
    dest: /etc/security/pwquality.conf
    state: present
    regexp: '^minlen = 14'
    line: 'minlen = 14'

- name: Set minimum password class
  lineinfile:
    dest: /etc/security/pwquality.conf
    state: present
    regexp: '^minclass = 4'
    line: 'minclass = 4'

- name: Adjust common-auth file
  template:
    src: common_auth.j2
    dest: /etc/pam.d/common-auth
    owner: root
    group: root
    mode: '644'
  when: passwords_faillock

- name: Configure PAM faillock
  lineinfile:
    dest: /etc/pam.d/common-account
    state: present
    regexp: '^account     required      pam_faillock.so'
    line: 'account     required      pam_faillock.so'
  when: passwords_faillock

- name: Adjust faillock configuration
  template:
    src: faillock_conf.j2
    dest: /etc/security/faillock.conf
    owner: root
    group: root
    mode: '644'
  when: passwords_faillock
