uninstall_services:
  - cups
  - isc-dhcp-server
  - slapd
  - nfs-kernel-server
  - bind9
  - vsftpd
  - apache2
  - dovecot-imapd
  - dovecot-pop3d
  - samba
  - squid
  - snmp
  - nis
  - rsync
  - rsh-client
  - talk
  - telnet
  - ldap-utils
  - rpcbind

network_interface_name: ens3

auditd_rules:
  - '-w /etc/sudoers -p wa -k scope'
  - '-w /etc/sudoers.d -p wa -k scope'
  - '-a always,exit -F arch=b64 -C euid!=uid -F auid!=unset -S execve -k user_emulation'
  - '-a always,exit -F arch=b32 -C euid!=uid -F auid!=unset -S execve -k user_emulation'
  - '-w /var/log/sudo.log -p wa -k sudo_log_file'
  - '-a always,exit -F arch=b64 -S adjtimex,settimeofday,clock_settime -k time-change'
  - '-a always,exit -F arch=b32 -S adjtimex,settimeofday,clock_settime -k time-change'
  - '-w /etc/localtime -p wa -k time-change'
  - '-a always,exit -F arch=b64 -S sethostname,setdomainname -k system-locale'
  - '-a always,exit -F arch=b32 -S sethostname,setdomainname -k system-locale'
  - '-w /etc/issue -p wa -k system-locale'
  - '-w /etc/issue.net -p wa -k system-locale'
  - '-w /etc/hosts -p wa -k system-locale'
  - '-w /etc/networks -p wa -k system-locale'
  - '-w /etc/network/ -p wa -k system-locale'
  - '-a always,exit -F arch=b64 -S creat,open,openat,truncate,ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -k access'
  - '-a always,exit -F arch=b64 -S creat,open,openat,truncate,ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -k access'
  - '-a always,exit -F arch=b32 -S creat,open,openat,truncate,ftruncate -F exit=-EACCES -F auid>=1000 -F auid!=unset -k access'
  - '-a always,exit -F arch=b32 -S creat,open,openat,truncate,ftruncate -F exit=-EPERM -F auid>=1000 -F auid!=unset -k access'
  - '-w /etc/group -p wa -k identity'
  - '-w /etc/passwd -p wa -k identity'
  - '-w /etc/gshadow -p wa -k identity'
  - '-w /etc/shadow -p wa -k identity'
  - '-w /etc/security/opasswd -p wa -k identity'
  - '-a always,exit -F arch=b32 -S mount -F auid>=1000 -F auid!=unset -k mounts'
  - '-a always,exit -F arch=b64 -S mount -F auid>=1000 -F auid!=unset -k mounts'
  - '-w /var/run/utmp -p wa -k session'
  - '-w /var/log/wtmp -p wa -k session'
  - '-w /var/log/btmp -p wa -k session'
  - '-w /var/log/lastlog -p wa -k logins'
  - '-w /var/run/faillock -p wa -k logins'
  - '-a always,exit -F arch=b64 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=unset -k delete'
  - '-a always,exit -F arch=b32 -S unlink,unlinkat,rename,renameat -F auid>=1000 -F auid!=unset -k delete'
  - '-w /etc/apparmor/ -p wa -k MAC-policy'
  - '-w /etc/apparmor.d/ -p wa -k MAC-policy'
  - '-a always,exit -S all -F path=/usr/bin/chcon -F perm=x -F auid>=1000 -F auid!=-1 -F key=perm_chng'
  - '-a always,exit -F path=/usr/bin/setfacl -F perm=x -F auid>=1000 -F auid!=unset -k perm_chng'
  - '-a always,exit -F path=/usr/bin/chacl -F perm=x -F auid>=1000 -F auid!=unset -k priv_cmd'
  - '-a always,exit -F path=/usr/sbin/usermod -F perm=x -F auid>=1000 -F auid!=unset -k usermod'
  - '-a always,exit -F arch=b64 -S init_module,finit_module,delete_module -F auid>=1000 -F auid!=unset -k kernel_modules'
  - '-a always,exit -F path=/usr/bin/kmod -F perm=x -F auid>=1000 -F auid!=unset -k kernel_modules'

sshd_allowed_users:
  - ubuntu

sshd_ciphers:
  - chacha20-poly1305@openssh.com
  - aes256-gcm@openssh.com
  - aes128-gcm@openssh.com
  - aes256-ctr
  - aes192-ctr
  - aes128-ctr

sshd_macs:
  - hmac-sha2-512-etm@openssh.com
  - hmac-sha2-256-etm@openssh.com
  - hmac-sha2-512
  - hmac-sha2-256

sshd_kex:
  - curve25519-sha256
  - curve25519-sha256@libssh.org
  - diffie-hellman-group14-sha256
  - diffie-hellman-group16-sha512
  - diffie-hellman-group18-sha512
  - ecdh-sha2-nistp521
  - ecdh-sha2-nistp384
  - ecdh-sha2-nistp256
  - diffie-hellman-group-exchange-sha256

passwords_faillock: false
passwords_deny_after_tries: 5
passwords_fail_interval: 900
passwords_unlock_time: 600