---
- name: Create docker group
  group:
    name: docker
    state: present

- name: Add specified users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ docker_users }}"